### ISSUE TITLE
ERROR: TypeError - expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by himanshusaini-fa** [aws/aws-elastic-beanstalk-cli#43]
### System Info
OS: Windows 10
Shell: cmd

### Description
**ERROR: TypeError - expected str, bytes or os.PathLike object, not NoneType**
I get this error while following [this guide from aws](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_express.html) , when I use "**eb deploy**". 

**If I'm supposed to raise it somewhere else please Point to it.**

Here are my verbose logs
```
eb deploy --verbose
INFO: Deploying code to node-express-env in region us-east-1
INFO: Getting version label from git with git-describe
INFO: Pushing local code to codecommit with git-push
INFO: Traceback (most recent call last):
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\core\ebrun.py", line 62, in run_app
    app.run()
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\cement\core\foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\cement\core\controller.py", line 472, in _dispatch
    return func()
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\cement\core\controller.py", line 478, in _dispatch
    return func()
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\core\abstractcontroller.py", line 92, in default
    self.do_command()
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\controllers\deploy.py", line 79, in do_command
    deployops.deploy(self.app_name, self.env_name, self.version, self.label,
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\operations\deployops.py", line 48, in deploy
    app_version_label = commonops.create_codecommit_app_version(
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\operations\commonops.py", line 583, in create_codecommit_app_version
    source_control.push_codecommit_code()
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\objects\sourcecontrol.py", line 324, in push_codecommit_code
    stdout, stderr, exitcode = self._run_cmd(
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\ebcli\objects\sourcecontrol.py", line 519, in _run_cmd
    stdout, stderr, exitcode = exec_cmd(cmd)
  File "c:\users\himanshu\.ebcli-virtual-env\lib\site-packages\cement\utils\shell.py", line 40, in exec_cmd
    proc = Popen(cmd_args, *args, **kw)
  File "c:\python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "c:\python38\lib\subprocess.py", line 1247, in _execute_child
    args = list2cmdline(args)
  File "c:\python38\lib\subprocess.py", line 549, in list2cmdline
    for arg in map(os.fsdecode, seq):
  File "c:\python38\lib\os.py", line 818, in fsdecode
    filename = fspath(filename)  # Does type-checking of `filename`.
TypeError: expected str, bytes or os.PathLike object, not NoneType

INFO: TypeError - expected str, bytes or os.PathLike object, not NoneType
```

**Comment by tgreco** [comment]
Having the same issue.

**Comment by varfolomejev** [comment]
the same problem. I'm using [deploy guide](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_nodejs_express.html)

**Comment by manishie** [comment]
Any update here?  Same problem, and I wasn't able to install any previous versions of the cli successfully.

**Comment by Palakpatel67** [comment]
@himanshusaini-fa thanks for reporting this issue. Could you tell which Python version are you using?

**Comment by himanshusaini-fa** [comment]
> @himanshusaini-fa thanks for reporting this issue. Could you tell which Python version are you using?

Hi @Palakpatel67.  it's in the verbose. Python 3.8.

**Comment by Palakpatel67** [comment]
@himanshusaini-fa  I was finally able to reproduce the issue. Issue here is CLI look for current repository name based on the current branch name ( `git config --get branch.master.remote`) while deploying application via codecommit and if remote branch is not set in `.git/config` file, it returns "none" which results in `TypeError` . this values are set in `.git/config` while initializing an application with codecommit. 

In case if branch details are not set, you can add your remote branch configurations in `.git/config`, 
```
[branch "master"]
	remote = codecommit-origin
	merge = refs/heads/master
```

Note: in this example codecommit branch name is `master`

let us know if you have any questions. thanks!

**Comment by Palakpatel67** [comment]
Closing this issue as there has been no update for an extended period of time.

**Comment by dadooda** [comment]
The only thing which worked for me was downgrading to 3.18.1 (buggy EB 3.19 already built using the CLI setup scripts):

```
$ cd ~/.ebcli-virtual-env
$ bin/pip install awsebcli==3.18.1
$ eb --version
```

**Comment by nvquangth** [comment]
@Palakpatel67 thank you so much, it worked for me.

**Comment by equivalent** [comment]
same issue when eb init with code commit.  The way I've fixed it is I've  deleted the `.elasticbanstalk` folder and done `eb init` again without the code commit  :roll_eyes:

**Comment by liquiddandruff** [comment]
Amazingly this bug is still not fixed. The stack trace I get after --verbose is the same in the OP. 

```
$ eb --version
EB CLI 3.19.4 (Python 3.8.2)
```

**Comment by waissbluth** [comment]
Can someone reopen this? It is still going on

**Comment by JakovlevDS** [comment]
Faced the same issue with 
```
$ eb --version
EB CLI 3.20.2 (Python 3.9.7)
```

@dadooda's [solution](https://github.com/aws/aws-elastic-beanstalk-cli/issues/43#issuecomment-782520229) works like a charm.

**Comment by Fusseldieb** [comment]
Issue still persists

**Comment by Jahnvi203** [comment]
Hi do we need to create a new file called .git/config or are you taking about config.yaml @galiperkin?

**Comment by Lezgig** [comment]
> [branch "master"]
> 	remote = codecommit-origin
> 	merge = refs/heads/master

same, Palakpatel67's suggestion worked just fine for me but I still find this solution a bit hacky
