### ISSUE TITLE
UnicodeError -- eb appversion

### ISSUE THREAD

**Issue by erikhSSI** [aws/aws-elastic-beanstalk-cli#56]
### Description

interactive mode does not work

### Steps to reproduce

eb appversion

### Observed result

ERROR: UnicodeEncodeError - 'latin-1' codec can't encode character '\u25bc' in position 64: ordinal not in range(256)

```

2020-11-24 23:29:26,876 (INFO) eb : Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/home/vagrant/.local/lib/python3.7/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/vagrant/.local/lib/python3.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/vagrant/.local/lib/python3.7/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/controllers/appversion.py", line 43, in do_command
    self.interactive_list_version()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/controllers/appversion.py", line 53, in interactive_list_version
    appversionops.display_versions(self.app_name, self.env_name, app_versions)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/operations/appversionops.py", line 75, in display_versions
    screen.start_version_screen(data, VersionScreen.APP_VERSIONS_TABLE_NAME)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/appversion.py", line 94, in start_version_screen
    self.draw('app_versions')
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/screen.py", line 120, in draw
    self.show_help_line()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/appversion.py", line 116, in show_help_line
    term.echo_line(text)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/term.py", line 106, in echo_line
    echo_on_line(counter, *strings)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/term.py", line 146, in echo_on_line
    io.echo(*strings)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/core/io.py", line 84, in echo
    print_(*_convert_to_strings(args), **kwargs)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25bc' in position 64: ordinal not in range(256)

2020-11-24 23:29:26,881 (INFO) eb : UnicodeEncodeError - 'latin-1' codec can't encode character '\u25bc' in position 64: ordinal not in range(256)
```

### Expected result

interactive mode to work

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: ubuntu 12.04
2. EBCLI version: 3.19.2

**Comment by Palakpatel67** [comment]
@erikhSSI thanks for reporting this issue. We will look into this and post any updates to this issue.

**Comment by Palakpatel67** [comment]
This ishould be fixed in awsebcli version [3.19.3](https://pypi.org/project/awsebcli/3.19.3/).

**Comment by erikhSSI** [comment]
Upgraded to 3.19.3. Still doesn't work

```
 $ eb --version
EB CLI 3.19.3 (Python 3.7.9)
```

`eb appversion --debug`

```
2021-01-15 23:08:22,314 (INFO) eb : Traceback (most recent call last):
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/core/ebrun.py", line 62, in run_app
    app.run()
  File "/home/vagrant/.local/lib/python3.7/site-packages/cement/core/foundation.py", line 797, in run
    return_val = self.controller._dispatch()
  File "/home/vagrant/.local/lib/python3.7/site-packages/cement/core/controller.py", line 472, in _dispatch
    return func()
  File "/home/vagrant/.local/lib/python3.7/site-packages/cement/core/controller.py", line 478, in _dispatch
    return func()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/core/abstractcontroller.py", line 92, in default
    self.do_command()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/controllers/appversion.py", line 43, in do_command
    self.interactive_list_version()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/controllers/appversion.py", line 53, in interactive_list_version
    appversionops.display_versions(self.app_name, self.env_name, app_versions)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/operations/appversionops.py", line 75, in display_versions
    screen.start_version_screen(data, VersionScreen.APP_VERSIONS_TABLE_NAME)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/appversion.py", line 94, in start_version_screen
    self.draw('app_versions')
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/screen.py", line 120, in draw
    self.show_help_line()
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/appversion.py", line 116, in show_help_line
    term.echo_line(text)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/term.py", line 106, in echo_line
    echo_on_line(counter, *strings)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/display/term.py", line 146, in echo_on_line
    io.echo(*strings)
  File "/home/vagrant/.local/lib/python3.7/site-packages/ebcli/core/io.py", line 84, in echo
    print_(*_convert_to_strings(args), **kwargs)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u25bc' in position 64: ordinal not in range(256)

2021-01-15 23:08:22,318 (INFO) eb : UnicodeEncodeError - 'latin-1' codec can't encode character '\u25bc' in position 64: ordinal not in range(256)
```
