### ISSUE TITLE
CodeCommit Integration Broken

### ISSUE THREAD

**Issue by senstbr** [aws/aws-elastic-beanstalk-cli#8]
### Description
When attempting to run 'eb init' with a CodeCommit integration, errors are occurring within the eb cli as mentioned in the message below -

Could not set CodeCommit branch, run with '--debug' to get the full error

### Steps to reproduce

Steps outlined in the AWS Docs listed below - https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/eb-cli-codecommit.html#eb-cli-codecommit-existing

### Observed result

Could not set CodeCommit branch, run with '--debug' to get the full error

Please provide command output with `--debug` flag set

2020-01-29 15:59:49,911 (DEBUG) ebcli.lib.aws : Making api call: (codecommit, get_repository) to region: us-east-1 with args:{'repositoryName': u'nodejs-test'}
2020-01-29 15:59:50,051 (DEBUG) ebcli.lib.aws : API call finished, status = 200
2020-01-29 15:59:50,051 (DEBUG) ebcli.lib.aws : Response: {u'repositoryMetadata': {u'creationDate': datetime.datetime(2019, 3, 28, 11, 1, 23, 324000, tzinfo=tzlocal()), u'defaultBranch': u'master', u'repositoryName': u'nodejs-test', u'cloneUrlSsh': u'ssh://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test', u'lastModifiedDate': datetime.datetime(2020, 1, 29, 13, 58, 53, 821000, tzinfo=tzlocal()), u'repositoryDescription': u'Created with EB CLI', u'cloneUrlHttp': u'https://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test', u'repositoryId': u'd67a550e-91ce-4903-a41a-ca19361f3b84', u'Arn': u'arn:aws:codecommit:us-east-1:AccountID:nodejs-test', u'accountId': u'AccountID'}, 'ResponseMetadata': {'date': 'Wed, 29 Jan 2020 23:59:49 GMT', 'RetryAttempts': 0, 'HTTPStatusCode': 200, 'RequestId': '64213593-3619-4991-b697-297550970de6'}}
2020-01-29 15:59:50,052 (DEBUG) ebcli.objects.sourcecontrol : Adding remote: git remote add codecommit-origin https://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test
2020-01-29 15:59:50,064 (DEBUG) ebcli.objects.sourcecontrol : Remote already exists, performing: git remote set-url codecommit-origin https://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test
2020-01-29 15:59:50,076 (DEBUG) ebcli.objects.sourcecontrol :                 git remote set-url --push codecommit-origin https://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test
2020-01-29 15:59:50,090 (DEBUG) ebcli.objects.sourcecontrol : git remote result: 
2020-01-29 15:59:50,090 (DEBUG) ebcli.controllers.initialize : Setting up an existing branch
2020-01-29 15:59:50,090 (DEBUG) ebcli.objects.sourcecontrol : Fetching remote branches using remote URL: git fetch https://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test
2020-01-29 15:59:53,860 (DEBUG) ebcli.objects.sourcecontrol : git fetch error: From https://git-codecommit.us-east-1.amazonaws.com/v1/repos/nodejs-test
 * branch            HEAD       -> FETCH_HEAD
2020-01-29 15:59:53,861 (DEBUG) ebcli.objects.sourcecontrol : git fetch result: 
2020-01-29 15:59:53,888 (DEBUG) ebcli.objects.sourcecontrol : git branch --set-upstream-to error: error: the requested upstream branch 'codecommit-origin/master' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
Could not set CodeCommit branch, run with '--debug' to get the full error

### Expected result
EB Init succeeds and ability to manage EB environments with CodeCommit integration 

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS:  MacOs
2. EB CLI version: EB CLI 3.17.0 (Python 2.7.1)

Tracked error down to 'setup_existing_codecommit_branch' function linked below [1] currently testing to see if updating the Git class to use 'origin' rather than 'codecommit-origin' as the remote branch name. [2]

[1] EB CLI 'setup_existing_codecommit_branch' Function Definition - https://github.com/aws/aws-elastic-beanstalk-cli/blob/861b16757da0891ad2b7f40893c1278d07d982e3/ebcli/objects/sourcecontrol.py#L433

[2] EB CLI 'Git' Class Definition  https://github.com/aws/aws-elastic-beanstalk-cli/blob/861b16757da0891ad2b7f40893c1278d07d982e3/ebcli/objects/sourcecontrol.py#L117

**Comment by ChaseAllbee** [comment]
Hey senstbr,

Thanks for reaching out about this issue. I'm going to see if this issue is reproducible for us with the steps listed above. If it is I'll reach out with either a solution or (if the issue is on the ebcli) a plan to fix the issue in the codebase.

**Comment by ChaseAllbee** [comment]
Hello again senstbr,

I've so far been unable to reproduce the issue here. I'm hoping to get a little more information from you to see if I can nail down what's happening here. Could you provide the following information?

1) Does the ebcli prompt you to select a repository before the function call you posted above?
2) Does the ebcli prompt you to select a branch name before the function call you posted above? If so, what branch did you select?
3) Have you run `git fetch` while in this repo locally? If so does it run without issue?

**Comment by halcarleton** [comment]
Closing this issue as there has been no update for an extended period of time.

**Comment by gahlers** [comment]
I encountered this issue as well and eventhough i used ssh in cloning the repo in my machine.. when i try to do an eb init.. it tells me that the Requested URL doesnt exists. 

Tried git fetch and it works but not the eb-init section.

**Comment by halcarleton** [comment]
This should be fixed in v3.18.2

**Comment by gahlers** [comment]
Hi @halcarleton i have updated my eb cli to v3.18.2 but i am still getting the same error. Just to give you an idea of my setup, i have an existing repository, and an existing branch. So whenever I do eb init, and it asked me to choose if i wanted to use codecommit, i say yes and choose the existing repo and branch.. after choosing the branch, it throws me that there is an error which is the same with what i used to have before,
